// <auto-generated />
namespace MercadoVentasTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Seagregaelcarritoalusuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seagregaelcarritoalusuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201912172221571_Se agrega el carrito al usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
