// <auto-generated />
namespace MercadoVentasTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DatosinicialesentidadCategoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatosinicialesentidadCategoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201912071634203_Datos iniciales entidad Categoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
