// <auto-generated />
namespace MercadoVentasTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DatosinicialesenentidadPalabra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatosinicialesenentidadPalabra));
        
        string IMigrationMetadata.Id
        {
            get { return "201912161224214_Datos iniciales en entidad Palabra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
