// <auto-generated />
namespace MercadoVentasTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CampoIdUsuarioagregadoenUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampoIdUsuarioagregadoenUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201912042233507_Campo IdUsuario agregado en User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
