// <auto-generated />
namespace MercadoVentasTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeagregaPrecioActualalusuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeagregaPrecioActualalusuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201912172310395_Se agrega PrecioActual al usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
