// <auto-generated />
namespace MercadoVentasTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CampoApellidoobligatorioalcrearunusuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampoApellidoobligatorioalcrearunusuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201912081342180_Campo Apellido obligatorio al crear un usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
